### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by pablorq** [Dallas-Makerspace/Inventory#3]
Hi!

I've done the install steps but it doesn't work.

Step by step to reproduce the issue:
- Unzip files to /www
- core.php.default copy to core.php
- database.php.default copy to database.php
- Create database 'inventory'
- core.php: no changes
- database.php: update db 'inventory' and user:pass
- Firefox: http://127.0.0.1/Inventory/
Notice (1024): Please change the value of 'Security.salt' in app/Config/core.php to a salt value specific to your application [CORE\Cake\Utility\Debugger.php, line 850]

Notice (1024): Please change the value of 'Security.cipherSeed' in app/Config/core.php to a numeric (digits only) seed value specific to your application [CORE\Cake\Utility\Debugger.php, line 854]

Any idea?

**Comment by denzuko** [comment]
Try updating `app/Config/core.php`:192 and `app/Config/core.php`:187 to a new assigned values.

The best way to do so would be with the `openssl(1)` command like so:

#### How to generate a new cipherSeed
`openssl prime -generate -bits 32`


#### How to generate a new cipherSeed
`openssl prime -generate -bits 128 -hex`
