### ISSUE TITLE
 Dockerfile parse error line 4: ARG requires exactly one argument

### ISSUE THREAD

**Issue by rizwan92** [Dallas-Makerspace/Inventory#5]
when i ran this command 
`docker-compose up
`
i got this error 
` Dockerfile parse error line 4: ARG requires exactly one argument`

**Comment by dwinurhadia** [comment]
Same here

**Comment by denzuko** [comment]
Been playing around with a better stack centered around docker swarm and hhvm so we may have to revamp this Dockerfile to resolve this issue and modernize it to the current standards.

**Comment by denzuko** [comment]
We'll be closing this in favor of addressing version 2.0 in Issue #9
